Repository aiverify-foundation/aiverify, pull requests merged in 2023-07, with the labels that each got.

#121 included flake8 file to allow more characters
  .flake8
Labels: need-review, need-testing

#115 107 fix security issue with scipy v193
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/algorithms/fairness_metrics_toolbox_for_classification/poetry.lock
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/algorithms/fairness_metrics_toolbox_for_classification/pyproject.toml
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/algorithms/fairness_metrics_toolbox_for_classification/requirements.txt
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-regression/algorithms/fairness_metrics_toolbox_for_regression/poetry.lock
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-regression/algorithms/fairness_metrics_toolbox_for_regression/pyproject.toml
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-regression/algorithms/fairness_metrics_toolbox_for_regression/requirements.txt
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/poetry.lock
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/pyproject.toml
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/requirements.txt
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/poetry.lock
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/pyproject.toml
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/requirements.txt
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/poetry.lock
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/pyproject.toml
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/requirements.txt
  stock-plugins/aiverify.stock.partial-dependence-plot/algorithms/partial_dependence_plot/poetry.lock
  stock-plugins/aiverify.stock.partial-dependence-plot/algorithms/partial_dependence_plot/pyproject.toml
  stock-plugins/aiverify.stock.partial-dependence-plot/algorithms/partial_dependence_plot/requirements.txt
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/poetry.lock
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/pyproject.toml
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/requirements.txt
  stock-plugins/aiverify.stock.shap-toolbox/algorithms/shap_toolbox/poetry.lock
  stock-plugins/aiverify.stock.shap-toolbox/algorithms/shap_toolbox/pyproject.toml
  stock-plugins/aiverify.stock.shap-toolbox/algorithms/shap_toolbox/requirements.txt
  test-engine-app/poetry.lock
  test-engine-app/pyproject.toml
  test-engine-app/requirements.txt
  test-engine-core-modules/poetry.lock
  test-engine-core-modules/pyproject.toml
  test-engine-core-modules/requirements.txt
  test-engine-core/dist/test_engine_core-0.9.0.tar.gz
  test-engine-core/poetry.lock
  test-engine-core/pyproject.toml
  test-engine-core/requirements.txt
Labels: blocked, need-review, need-testing

#109 chore/create config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: need-review

#106 fix/typo in process checklist
  stock-plugins/aiverify.stock.process-checklist/dist/aiverify.stock.process_checklist-0.9.1.zip
  stock-plugins/aiverify.stock.process-checklist/inputs/config_reproducibility.ts
Labels: need-review

#137 fix/change label tag
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: need-review

#140 docs/change filename
  docs/using-toolkit-step-by-step/test-ai-model-and-generate-report/0-intro.md
  docs/using-toolkit-step-by-step/test-ai-model-and-generate-report/4-select-testing-dataset.md
  docs/using-toolkit-step-by-step/test-ai-model-and-generate-report/5-select-ground-truth-dataset.md
  docs/using-toolkit-step-by-step/test-ai-model-and-generate-report/7-provide-test-args.md
Labels: documentation, need-review

#148 docs/update recommend python version
  docs/getting-started/source-code-setup.md
Labels: documentation, need-review

#151 Update documentation
  getting-started/prepare-image/index.html
  getting-started/prepare-tabular/index.html
  getting-started/source-code-setup/index.html
  sitemap.xml
  sitemap.xml.gz
  using-toolkit-step-by-step/test-ai-model-and-generate-report/0-intro/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/4-select-testing-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/5-select-ground-truth-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/7-provide-test-args/index.html
Labels: documentation, automerge
