Repository aiverify-foundation/aiverify, pull requests merged in 2023-08, with the labels that each got.

#147 Modified code to process message in a seperate process initially inst…
  test-engine-app/test_engine_app/enums/process_status.py
  test-engine-app/test_engine_app/processing/task.py
  test-engine-app/test_engine_app/processing/task_processing.py
  test-engine-core-modules/src/sklearnmodel/sklearnmodel.py
Labels: totest

#164 Update documentation
  getting-started/docker-setup/index.html
  getting-started/source-code-setup/index.html
  sitemap.xml
  sitemap.xml.gz
Labels: documentation, automerge

#172 Unit tests covering key features in Project - Report Design flow
  ai-verify-portal/.eslintignore
  ai-verify-portal/__mocks__/ai-verify-shared-library/lib.ts
  ai-verify-portal/__mocks__/mockGlobals.ts
  ai-verify-portal/__mocks__/mockGqlResponse.ts
  ai-verify-portal/__mocks__/mockPlugins.ts
  ai-verify-portal/__mocks__/plugins.ts
  ai-verify-portal/__mocks__/server/pluginManager.ts
  ai-verify-portal/__tests__/modules/__snapshots__/project.test.tsx.snap
  ai-verify-portal/__tests__/modules/plugins.test.tsx
  ai-verify-portal/__tests__/modules/project.test.tsx
  ai-verify-portal/jest.setup.js
  ai-verify-portal/next.config.js
  ai-verify-portal/package-lock.json
  ai-verify-portal/package.json
  ai-verify-portal/src/modules/projectTemplate/draggableWidget.tsx
Labels: frontend-portal
