Repository aiverify-foundation/aiverify, pull requests merged in 2025-04, with the labels that each got.

#472 Fix Image Corruption Toolbox compatibility issues with aiverify-test-engine-worker
  aiverify-apigw/aiverify_apigw/routers/test_dataset_router.py
  aiverify-apigw/aiverify_apigw/routers/test_model_router.py
  aiverify-test-engine-worker/src/aiverify_test_engine_worker/pipeline/scripts/algo_execute.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/aiverify_blur_corruptions/algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/aiverify_blur_corruptions/algo_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/aiverify_blur_corruptions/input.schema.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/aiverify_blur_corruptions/plugin_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/aiverify_digital_corruptions/algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/aiverify_digital_corruptions/algo_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/aiverify_digital_corruptions/input.schema.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/aiverify_digital_corruptions/plugin_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/aiverify_environment_corruptions/algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/aiverify_environment_corruptions/algo_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/aiverify_environment_corruptions/input.schema.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/aiverify_environment_corruptions/plugin_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/aiverify_general_corruptions/algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/aiverify_general_corruptions/algo_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/aiverify_general_corruptions/input.schema.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/aiverify_general_corruptions/plugin_init.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/tests/unit_tests/test_algo.py
Labels: bug-fix

#489 Fix python module caching issue
  aiverify-test-engine/aiverify_test_engine/utils/import_modules.py
  aiverify-test-engine/tests/duplicate_import_modules/duplicate/example_serializer.py
  aiverify-test-engine/tests/duplicate_import_modules/original/example_serializer.py
  aiverify-test-engine/tests/test_import_modules.py
  stock-plugins/user_defined_files/pipeline/sample_fashion_mnist_pytorch/fashionCustomClass.py
  stock-plugins/user_defined_files/pipeline/sample_fashion_mnist_pytorch/fashionMNISTPytorch.py
Labels: annoyance, bug-fix

#508 Update documentation
  getting-started/docker-setup/index.html
  getting-started/prepare-image/index.html
  getting-started/prepare-tabular/index.html
  getting-started/quick-start-guide/AIVT_2.0_quick_start_guide.pdf
  getting-started/quick-start-guide/index.html
  index.html
  res/AIVT_2.0_quick_start_guide.pdf
  sitemap.xml
  sitemap.xml.gz
Labels: documentation, automerge

#521 Update documentation
  introduction/AIVT 2.0 features/index.html
  sitemap.xml
  sitemap.xml.gz
Labels: documentation, automerge

#520 Unify model and pipeline behavior when running predict on a list of data
  .ci/run-unit-test.sh
  .github/workflows/v2-smoke-test.yml
  .vscode/launch.json
  aiverify-apigw/pyproject.toml
  aiverify-test-engine/aiverify_test_engine/io/lightgbmmodel/lightgbmmodel.py
  aiverify-test-engine/aiverify_test_engine/io/sklearnmodel/sklearnmodel.py
  aiverify-test-engine/aiverify_test_engine/io/tensorflowmodel/tensorflowmodel.py
  aiverify-test-engine/aiverify_test_engine/io/xgboostmodel/xgboostmodel.py
  stock-plugins/aiverify.stock.accumulated-local-effect/algorithms/accumulated_local_effect/aiverify_accumulated_local_effect/algo.py
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/algorithms/fairness_metrics_toolbox_for_classification/aiverify_fairness_metrics_toolbox_for_classification/algo.py
  stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-regression/algorithms/fairness_metrics_toolbox_for_regression/aiverify_fairness_metrics_toolbox_for_regression/algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/blur_corruptions/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/digital_corruptions/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/environment_corruptions/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/.vscode/launch.json
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/README.md
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.image-corruption-toolbox/algorithms/general_corruptions/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.partial-dependence-plot/algorithms/partial_dependence_plot/aiverify_partial_dependence_plot/algo.py
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/.vscode/settings.json
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/README.md
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/aiverify_robustness_toolbox/algo.py
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/tests/e2e/test_e2e.py
  stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/tests/unit_tests/test_algo.py
  stock-plugins/aiverify.stock.shap-toolbox/algorithms/shap_toolbox/aiverify_shap_toolbox/algo.py
  stock-plugins/user_defined_files/pipeline/mc_image_fashion/fashionCustomClass.py
  stock-plugins/user_defined_files/pipeline/mc_image_fashion/fashion_mnist_lr_pipeline.sav
  stock-plugins/user_defined_files/pipeline/sample_fashion_mnist_sklearn/fashionCustomClass.py
  stock-plugins/user_defined_files/pipeline/sample_fashion_mnist_sklearn/fashion_mnist_lr_pipeline.sav
Labels: High Priority, bug-fix, High Defect

#525 Update documentation
  detailed-guide/explainability-test/index.html
  detailed-guide/fairness-test/index.html
  detailed-guide/robustness-test/index.html
  res/detailed-guide/AIVT_2_0_Fairness/index.html
  res/detailed-guide/AIVT_2_0_PDP/index.html
  res/detailed-guide/AIVT_2_0_Robustness/index.html
  sitemap.xml
  sitemap.xml.gz
Labels: documentation, automerge

#527 Update documentation
  others/compatibility/index.html
  sitemap.xml.gz
Labels: documentation, automerge

#528 Update documentation
  404.html
  appendix/standalone-vs-pipeline/index.html
  appendix/use-fairness-tree/index.html
  detailed-guide/aiverify-process-checklist/index.html
  detailed-guide/explainability-test/index.html
  detailed-guide/fairness-test/index.html
  detailed-guide/input-preparation/preparation-of-input-files/index.html
  detailed-guide/input-preparation/prepare-image/index.html
  detailed-guide/input-preparation/prepare-tabular/index.html
  detailed-guide/installation-using-kubernetes/index.html
  detailed-guide/plugin-management/index.html
  detailed-guide/robustness-test/index.html
  detailed-guide/supported-versions/index.html
  detailed-guide/veritas-process-checklist/index.html
  getting-started/docker-setup/index.html
  getting-started/index.html
  getting-started/source-code-setup/index.html
  how-to/connect-to-ai-model-api/index.html
  index.html
  introduction/AIVT 2.0 features/index.html
  introduction/how-it-works/index.html
  others/compatibility/index.html
  others/faq/index.html
  quick-start-guide/index.html
  res/detailed-guide/AIVT_2_0_Fairness/index.html
  res/detailed-guide/AIVT_2_0_PDP/index.html
  res/detailed-guide/AIVT_2_0_Robustness/index.html
  sitemap.xml.gz
  trouble-shooting/troubleshooting/index.html
  user-interface-features/asset-manager-page/index.html
  user-interface-features/canvas-page/index.html
  user-interface-features/homepage/index.html
  user-interface-features/input-blocks-page/index.html
  user-interface-features/plugin-manager-page/index.html
  user-interface-features/report-generating-page/index.html
  user-interface-features/report-template-manager-page/index.html
  using-toolkit-step-by-step/design-customized-report/0-intro/index.html
  using-toolkit-step-by-step/design-customized-report/1-create-new-project/index.html
  using-toolkit-step-by-step/design-customized-report/2-start-empty-canvas/index.html
  using-toolkit-step-by-step/design-customized-report/3-design-report-with-widgets/index.html
  using-toolkit-step-by-step/design-customized-report/4-using-global-variable/index.html
  using-toolkit-step-by-step/design-customized-report/5-add-new-pages/index.html
  using-toolkit-step-by-step/design-customized-report/6-using-widget-with-dependencies/index.html
  using-toolkit-step-by-step/design-customized-report/7-save-as-template/index.html
  using-toolkit-step-by-step/design-customized-report/8-export-as-plugin/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/0-intro/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/1-create-new-project/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/10-run-test-and-generate-report/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/2-select-template/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/3-design-the-report/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/4-select-testing-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/5-select-ground-truth-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/6-select-ai-model/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/7-provide-test-args/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/8-complete-process-checklist/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/9-select-fairness-metrics-using-fainess-tree/index.html
Labels: documentation, automerge

#530 Update documentation
  getting-started/index.html
  sitemap.xml.gz
Labels: documentation, automerge

#531 Update documentation
  others/compatibility/index.html
  sitemap.xml.gz
Labels: documentation, automerge

#532 Update documentation
  detailed-guide/supported-versions/index.html
  sitemap.xml.gz
Labels: documentation, automerge

#535 Update documentation
  404.html
  appendix/standalone-vs-pipeline/index.html
  appendix/use-fairness-tree/index.html
  detailed-guide/aiverify-process-checklist/index.html
  detailed-guide/explainability-test/index.html
  detailed-guide/fairness-test/index.html
  detailed-guide/input-preparation/preparation-of-input-files/index.html
  detailed-guide/input-preparation/prepare-image/index.html
  detailed-guide/input-preparation/prepare-tabular/index.html
  detailed-guide/installation-using-kubernetes/index.html
  detailed-guide/plugin-management/index.html
  detailed-guide/robustness-test/index.html
  detailed-guide/supported-versions/index.html
  detailed-guide/veritas-process-checklist/index.html
  getting-started/docker-setup/index.html
  getting-started/index.html
  getting-started/source-code-setup/index.html
  how-to/connect-to-ai-model-api/index.html
  index.html
  introduction/AIVT 2.0 features/index.html
  introduction/how-it-works/index.html
  others/compatibility/index.html
  others/faq/index.html
  quick-start-guide/index.html
  res/detailed-guide/AIVT_2_0_Fairness/index.html
  res/detailed-guide/AIVT_2_0_PDP/index.html
  res/detailed-guide/AIVT_2_0_Robustness/index.html
  sitemap.xml
  sitemap.xml.gz
  trouble-shooting/troubleshooting/index.html
  user-interface-features/asset-manager-page/index.html
  user-interface-features/canvas-page/index.html
  user-interface-features/homepage/index.html
  user-interface-features/input-blocks-page/index.html
  user-interface-features/plugin-manager-page/index.html
  user-interface-features/report-generating-page/index.html
  user-interface-features/report-template-manager-page/index.html
  using-toolkit-step-by-step/design-customized-report/0-intro/index.html
  using-toolkit-step-by-step/design-customized-report/1-create-new-project/index.html
  using-toolkit-step-by-step/design-customized-report/2-start-empty-canvas/index.html
  using-toolkit-step-by-step/design-customized-report/3-design-report-with-widgets/index.html
  using-toolkit-step-by-step/design-customized-report/4-using-global-variable/index.html
  using-toolkit-step-by-step/design-customized-report/5-add-new-pages/index.html
  using-toolkit-step-by-step/design-customized-report/6-using-widget-with-dependencies/index.html
  using-toolkit-step-by-step/design-customized-report/7-save-as-template/index.html
  using-toolkit-step-by-step/design-customized-report/8-export-as-plugin/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/0-intro/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/1-create-new-project/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/10-run-test-and-generate-report/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/2-select-template/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/3-design-the-report/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/4-select-testing-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/5-select-ground-truth-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/6-select-ai-model/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/7-provide-test-args/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/8-complete-process-checklist/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/9-select-fairness-metrics-using-fainess-tree/index.html
Labels: documentation, automerge

#536 Update documentation
  404.html
  appendix/faq/index.html
  appendix/standalone-vs-pipeline/index.html
  appendix/supported-versions/index.html
  appendix/use-fairness-tree/index.html
  detailed-guide/aiverify-process-checklist/index.html
  detailed-guide/explainability-test/index.html
  detailed-guide/fairness-test/index.html
  detailed-guide/input-preparation/preparation-of-input-files/index.html
  detailed-guide/input-preparation/prepare-image/index.html
  detailed-guide/input-preparation/prepare-tabular/index.html
  detailed-guide/installation-using-kubernetes/index.html
  detailed-guide/plugin-management/index.html
  detailed-guide/robustness-test/index.html
  detailed-guide/veritas-process-checklist/index.html
  getting-started/docker-setup/index.html
  getting-started/index.html
  getting-started/source-code-setup/index.html
  how-to/connect-to-ai-model-api/index.html
  index.html
  introduction/AIVT 2.0 features/index.html
  introduction/how-it-works/index.html
  others/compatibility/index.html
  quick-start-guide/index.html
  res/detailed-guide/AIVT_2_0_Fairness/index.html
  res/detailed-guide/AIVT_2_0_PDP/index.html
  res/detailed-guide/AIVT_2_0_Robustness/index.html
  sitemap.xml
  sitemap.xml.gz
  trouble-shooting/troubleshooting/index.html
  user-interface-features/asset-manager-page/index.html
  user-interface-features/canvas-page/index.html
  user-interface-features/homepage/index.html
  user-interface-features/input-blocks-page/index.html
  user-interface-features/plugin-manager-page/index.html
  user-interface-features/report-generating-page/index.html
  user-interface-features/report-template-manager-page/index.html
  using-toolkit-step-by-step/design-customized-report/0-intro/index.html
  using-toolkit-step-by-step/design-customized-report/1-create-new-project/index.html
  using-toolkit-step-by-step/design-customized-report/2-start-empty-canvas/index.html
  using-toolkit-step-by-step/design-customized-report/3-design-report-with-widgets/index.html
  using-toolkit-step-by-step/design-customized-report/4-using-global-variable/index.html
  using-toolkit-step-by-step/design-customized-report/5-add-new-pages/index.html
  using-toolkit-step-by-step/design-customized-report/6-using-widget-with-dependencies/index.html
  using-toolkit-step-by-step/design-customized-report/7-save-as-template/index.html
  using-toolkit-step-by-step/design-customized-report/8-export-as-plugin/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/0-intro/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/1-create-new-project/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/10-run-test-and-generate-report/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/2-select-template/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/3-design-the-report/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/4-select-testing-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/5-select-ground-truth-dataset/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/6-select-ai-model/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/7-provide-test-args/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/8-complete-process-checklist/index.html
  using-toolkit-step-by-step/test-ai-model-and-generate-report/9-select-fairness-metrics-using-fainess-tree/index.html
Labels: documentation, automerge
